apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  labels:
    app: nextjs-app
spec:
  type: LoadBalancer # Use ClusterIP for internal-only access
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80         # Public-facing port
      targetPort: 3000 # Port your Next.js app listens on
