name: App Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-2
  IMAGE_TAG: ${{ github.sha }}

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: Deploy
    runs-on: ["self-hosted", "hub-app"]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get secrets from AWS Secrets Manager
        id: get_secrets
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value \
            --secret-id aws_ecr_repo \
            --region ap-south-2 \
            --query SecretString \
            --output text)

          # Mask the entire secret to avoid leaks
          echo "::add-mask::$SECRET_JSON"

          echo "$SECRET_JSON" > secret.json

          # Extract and mask individual secret
          APP_ECR_REGISTRY=$(jq -r '.AWS_ECR_REPO' secret.json)

          echo "::add-mask::$APP_ECR_REGISTRY"

          echo "APP_ECR_REGISTRY=$APP_ECR_REGISTRY" >> $GITHUB_ENV

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker build \
            -t $APP_ECR_REGISTRY:hub-app-$IMAGE_TAG \
            -f Dockerfile . \
            --no-cache

          aws ecr get-login-password --region ap-south-2 | \
            docker login --username AWS --password-stdin $APP_ECR_REGISTRY

          echo "image=$APP_ECR_REGISTRY:hub-app-$IMAGE_TAG" >> $GITHUB_OUTPUT

          docker push $APP_ECR_REGISTRY:hub-app-$IMAGE_TAG

      - name: Deploying to QA-mimicry
        run: |
          docker rm -f $(docker ps -aqf "name=hub-app-container") || true
          docker run -d \
            -p 3000:3000 \
            --name hub-app-container \
            "$APP_ECR_REGISTRY:hub-app-$IMAGE_TAG"
